resolver: nightly-2016-08-21 
packages:
- location: '.'
- location: 
    git: https://github.com/byteally/dbrecord.git
    commit: d2cb4babf421eb38c219505e984106bc83fc7cc7


extra-deps: []

extra-package-dbs: []
