resolver: nightly-2016-08-21 
packages:
packages:
- location: '.'
- location: 
    git: https://github.com/byteally/dbrecord.git
    commit: 9f09c399c9f248cfbd2e748d2c8d7ede84947f5d

extra-deps: []

extra-package-dbs: []
